/* Generated by ./gen.sh from ./cap_version.in; do not edit. */

static const struct xlat cap_version[] = {
	XLAT(_LINUX_CAPABILITY_VERSION_1),
	XLAT(_LINUX_CAPABILITY_VERSION_2),
	XLAT(_LINUX_CAPABILITY_VERSION_3),
	XLAT_END
};
